# Generated by Django 2.1.3 on 2018-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='output_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
