# Generated by Django 2.1.3 on 2018-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('new', 'New'), ('in_progress', 'In-Progress'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=100),
        ),
    ]
